#!/bin/bash
# WSL Client Tunnels
# by Greg Lawler and Andy Rusch

#### Prerequisites ####
# Firefox 64-bit installed
# Putty 64-bit installed (https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)
# Your WSL Username and key are on jump_host

#### Firefox Config ####
# - Open Firefox and enter about:profiles in the URL bar
# - Create a new profile called "Tunnels"
# - Open Firefox with the Tunnels profile:
#    - Preferences -> General -> Network Settings -> Manual proxy configuration
#        SOCKS HOST: localhost
#        Port: 2080
#        SOCKS v5: check

##### Defaults
 : ${config:=tunnels.conf}
 : ${firefox_profile:=Tunnels}

# Exit on error
set -e

# Ensure Putty and Firefox are in $PATH.
export PATH="$PATH:/mnt/c/Program Files/Putty"
export PATH="$PATH:/mnt/c/Program Files/Mozilla Firefox"

function wsl_tunnel() {
  putty.exe -D 2080 $USER@$ssh_server > /dev/null 2>&1 &
}

function wsl_firefox() {
  firefox.exe -P $firefox_profile $client_url > /dev/null 2>&1 &
}

function wsl_client() {  
  while IFS=',' read -r client_service ssh_server client_url || [ -n "$line" ]; do
    if [[ $client_service == $jump_host ]]
      then
        wsl_tunnel "$ssh_server"
        sleep 1
        wsl_firefox "$client_service"
    fi  
  done < $config
}

function wsl_locations() {
    echo Usage: `basename $0` '{location}' 1>&2
    echo ""
    echo "Available locations in" $config
    while IFS=',' read -r client_service ssh_server client_url; do
        echo "$client_service" 
    done < $config
}

if [ $# -eq 0 ]; # If no input, show available locations
then
    wsl_locations
    exit 1
else
    jump_host=$1
    wsl_client "$jump_host"
fi
